### ISSUE TITLE
LNbits breaking change 

### ISSUE THREAD

**Issue by Bashy** [fiatjaf/makeinvoice#5]
As described in https://github.com/nbd-wtf/satdress/issues/39
The following commit https://github.com/fiatjaf/makeinvoice/commit/6b7857882139cd53ec85ab994fd9627a29979092 makes `makeinvoice` not working with LNbits API.

**Comment by Bashy** [comment]
`unhashed_description` value needs to be provided in hex format.

**Comment by fiatjaf** [comment]
Fixed in c5d0f65c88a506a07055d4d29c1cdc05661a1597
